DROP TABLE IF EXISTS "__drizzle_migrations";
DROP TABLE IF EXISTS dev_technology;
DROP TABLE IF EXISTS dope_dev;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS technology;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS user;
