INSERT INTO
  technology (name)
VALUES
  ('.NET Core'),
  ('.NET Framework'),
  ('3D Modeling'),
  ('Agile'),
  ('AJAX'),
  ('Angular.js'),
  ('Ansible'),
  ('Antivirus'),
  ('API-first'),
  ('App Shell'),
  ('ARCore'),
  ('ARKit'),
  ('Asana'),
  ('ASP'),
  ('ASP.NET'),
  ('Atom'),
  ('Augmented Reality'),
  ('AWS'),
  ('Azure'),
  ('Azure Functions'),
  ('Babel'),
  ('Backbone.js'),
  ('Bash/Shell'),
  ('Bitbucket'),
  ('Blazor'),
  ('Blazor Server'),
  ('Blazor WebAssembly'),
  ('C'),
  ('C#'),
  ('C++'),
  ('CFML'),
  ('Chai'),
  ('CI/CD'),
  ('CircleCI'),
  ('Cloud Computing'),
  ('ColdFusion'),
  ('Confluence'),
  ('Continuous Delivery'),
  ('Continuous Deployment'),
  ('Continuous Integration'),
  ('Cordova'),
  ('CORS'),
  ('CSP'),
  ('CSS'),
  ('Custom Elements'),
  ('Cypress'),
  ('D3.js'),
  ('Dart'),
  ('DDoS'),
  ('DevOps'),
  ('Django'),
  ('DNS'),
  ('Docker'),
  ('Electron'),
  ('Emacs'),
  ('Ember.js'),
  ('ESLint'),
  ('Express.js'),
  ('Fetch API'),
  ('Firebase'),
  ('Firewalls'),
  ('Flutter'),
  ('Flutter for Web'),
  ('FTP'),
  ('Git'),
  ('GitHub'),
  ('GitLab'),
  ('GitLab CI/CD'),
  ('Go'),
  ('Google Cloud Functions'),
  ('Google Cloud Platform'),
  ('Google PageSpeed Insights'),
  ('GraphQL'),
  ('Groovy'),
  ('Grunt'),
  ('Gulp'),
  ('HTML'),
  ('HTTP/2'),
  ('HTTPS'),
  ('IMAP'),
  ('Infrastructure as Code'),
  ('Intrusion Detection Systems'),
  ('Ionic'),
  ('IPv4'),
  ('IPv6'),
  ('Jasmine'),
  ('Java'),
  ('JavaScript'),
  ('Jenkins'),
  ('Jest'),
  ('JIRA'),
  ('JQuery'),
  ('JSON'),
  ('JSP'),
  ('Jupyter Notebook'),
  ('JWT'),
  ('Kanban'),
  ('Keras'),
  ('Kotlin'),
  ('Kubernetes'),
  ('Lambda'),
  ('Laravel'),
  ('Less'),
  ('Lighthouse'),
  ('LitElement'),
  ('Markdown'),
  ('Matplotlib'),
  ('Mercurial'),
  ('Meteor.js'),
  ('Microservices'),
  ('Mocha'),
  ('MongoDB'),
  ('Mongoose'),
  ('Mono'),
  ('MySQL'),
  ('Network Security'),
  ('Node.js'),
  ('NPM'),
  ('NumPy'),
  ('OAuth'),
  ('Objective-C'),
  ('OpenCV'),
  ('OpenID'),
  ('Oracle'),
  ('Pandas'),
  ('Parcel'),
  ('Perl'),
  ('PHP'),
  ('Plotly.js'),
  ('Polymer'),
  ('POP3'),
  ('PostgreSQL'),
  ('Prettier'),
  ('Progressive Web Apps'),
  ('Protractor'),
  ('PWA'),
  ('Python'),
  ('PyTorch'),
  ('R'),
  ('Rails'),
  ('React Native'),
  ('React Native for Web'),
  ('React.js'),
  ('Redis'),
  ('REST'),
  ('RESTful APIs'),
  ('Ruby'),
  ('Ruby on Rails'),
  ('Rust'),
  ('SAML'),
  ('Sass'),
  ('Scala'),
  ('Scikit-learn'),
  ('SciPy'),
  ('Scrum'),
  ('Selenium'),
  ('Sequelize'),
  ('Serverless'),
  ('Serverless Architecture'),
  ('Service Workers'),
  ('SFTP'),
  ('Shadow DOM'),
  ('Slack'),
  ('SMTP'),
  ('SOAP'),
  ('SonarQube'),
  ('Spring'),
  ('SQL'),
  ('SQLite'),
  ('SSH'),
  ('SSL/TLS'),
  ('Stencil'),
  ('Stylus'),
  ('Sublime Text'),
  ('Svelte'),
  ('SvelteKit'),
  ('SVN'),
  ('Swift'),
  ('TensorBoard'),
  ('TensorFlow'),
  ('TensorFlow.js'),
  ('Terraform'),
  ('Three.js'),
  ('Tor'),
  ('Travis CI'),
  ('Trello'),
  ('TypeScript'),
  ('Vim'),
  ('Virtual Reality'),
  ('VPN'),
  ('VR'),
  ('VS Code'),
  ('Vue.js'),
  ('Web App Manifest'),
  ('Web Components'),
  ('Web Performance'),
  ('Web Standards'),
  ('Web Vitals'),
  ('Web.dev'),
  ('WebAR'),
  ('WebAssembly'),
  ('WebGL'),
  ('Webpack'),
  ('WebPageTest'),
  ('WebRTC'),
  ('WebSockets'),
  ('WebStorm'),
  ('WebXR'),
  ('WebXR Device API'),
  ('Wiki'),
  ('Xamarin'),
  ('Xamarin.Android'),
  ('Xamarin.Forms'),
  ('Xamarin.iOS'),
  ('Xamarin.Mac'),
  ('Xamarin.tvOS'),
  ('Xamarin.watchOS'),
  ('XML'),
  ('YAML'),
  ('Yarn');